package com.projeto.javasolutionshub.model;

public enum TypeCategory {
    ESTRUTURAS_DE_DADOS,
    PROGRAMACAO_ORIENTADA_A_OBJETOS,
    APIS_E_BIBLIOTECAS,
    GERENCIAMENTO_DE_MEMORIA,
    CONCORRENCIA_E_MULTITHREADING,
    ERROS_E_EXCECOES,
    DESEMPENHO_E_OTIMIZACAO,
    FERRAMENTAS_E_IDES
}